### ISSUE TITLE
Statistics when threads are stopped

### ISSUE THREAD

**Issue by rtaubes** [cankav/python_gil_demonstration#1]
Thank you very much for a clear demonstration of GIL in Python.

I started this code on my laptop and noticed that statistics when threads stopped is worse than the statistics at the begin. In my opinion, it will be better to wait when all thread really finished.
I added the similar to the processes functionality:
threads = []
...
   threads.append(thr)
   thr.start()
...
for thr in threads:
    thr.join()
As result, the statistics after threads are the same as the statistics at the begin.

**Comment by cankav** [comment]
You are right, threads should be joined. Thanks for pointing this out. I added the joins.
